export const GET_ONE_ARTICLE = "GET_ONE_ARTICLE" ; 
export const GET_LIKED_BY = "GET_LIKED_BY" ;

export const GET_FOLLOWERS = 'GET_FOLLOWERS' ; 
export const GET_FOLLOWINGS = 'GET_FOLLOWINGS' ;

export const GET_MY_BOOKMARKED = 'GET_MY_BOOKMARKED';



export const CREATE_COMMENT  = "CREATE_COMMENT" ; 
export const GET_COMMENTS = "GET_COMMENTS" ;
export const REMOVE_COMMENT = "REMOVE_COMMENT" ; 
