const GET_ONE_ARTICLE = 'GET_ONE_ARTICLE' ; 
const UPDATE_TIMELINE = 'UPDATE_TIMELINE' ; 

const GET_ARTICLES_NEAR_TO = 'GET_ARTICLES_NEAR_TO' ; 

const ADD_ARTICLE = 'ADD_ARTICLE' ; 
const GET_ALL_ARTICLE = 'GET_ALL_ARTICLE' ;
const GET_MY_ARTICLES = 'GET_MY_ARTICLES' ; 
const EDIT_ARTICLE = 'EDIT_ARTICLE' ; 
const DELETE_ARTICLE = 'DELETE_ARTICLE' ;