export const GET_ALL_LECTURES = 'GET_ALL_LECTURES'
export const LOAD_LECTURES = 'LOAD_LECTURES'

export const LOAD_COMMENTS = 'LOAD_COMMENTS'
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS'
export const CREATE_COMMENT = 'CREATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
